### ISSUE TITLE
Lock SG server

### ISSUE THREAD

**Issue by riyuejz** [AztecRabbit/Brainfuck-Psiphon#1]
Gimana caranya buat lock server nya..

**Comment by AztecRabbit** [comment]
Di `storage/psiphon/{port}/config-multi-tunnel.json` sama `storage/psiphon/{port}/config.json` EgressRegion isi jadi id negaranya, SG buat Singapura JP buat Jepang misalkan. Kosong = best performance. Edit di semua folder portnya, atau edit di port2 yang dipake.

**Comment by riyuejz** [comment]
Ok work gan.. dan kenapa ya setiap dpt 4mb setiap port selalu reconnect

**Comment by AztecRabbit** [comment]
Itu fiturnya. Soalnya setiap lebih dari 4MB, kecepatan internetnya dibates sama server psiphon jadi 16KB/s, jadi setiap lebih dari 4MB dan kecepatan kurang dari 20KB/s koneksi langsung diputus, terus konek ulang.
